#pragma once
#ifndef BASALT_RUNTIME_PLATFORM_WIN32_BUILD_CONFIG_H
#define BASALT_RUNTIME_PLATFORM_WIN32_BUILD_CONFIG_H

#if BASALT_DEV_BUILD

#define BASALT_TRACE_WINDOWS_MESSAGES 0

#endif // BASALT_DEV_BUILD

#endif // BASALT_RUNTIME_PLATFORM_WIN32_BUILD_CONFIG_H
