#pragma once
#ifndef BASALT_APP_BUILD_CONFIG_H
#define BASALT_APP_BUILD_CONFIG_H

#if BASALT_DEV_BUILD

#define BASALT_TRACE_WINDOWS_MESSAGES 0

#endif // BASALT_DEV_BUILD

#endif // BASALT_APP_BUILD_CONFIG_H
