name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, RelWithDebInfo, Release]

    runs-on: windows-2019

    env:
      FETCH_CONTENT_DIR: ./_deps

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: Write-Output "DXSDK_DIR=$env:TEMP/DXSDK" >> ${env:GITHUB_ENV}

    - name: Cache DirectX SDK
      uses: actions/cache@v2
      with:
        path: ${{ env.DXSDK_DIR }}
        key: June2010-v2

    - name: Cache CMake FetchContent
      uses: actions/cache@v2
      with:
        path: ${{ env.FETCH_CONTENT_DIR }}
        key: CMakeFC-${{ runner.os }}-${{ hashFiles('external/**') }}

    - name: Install DirectX SDK
      run: |
        if (-not(Test-Path -Path $env:DXSDK_DIR)) {
          Write-Host "Downloading..."
          $exePath = "$env:temp\DXSDK_Jun10.exe"
          (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)

          Write-Host "Installing..."
          Start-Process -Wait -FilePath $exePath -ArgumentList "/P ""$env:DXSDK_DIR"" /U"
        } else {
          Write-Host "Using cached DirectX SDK. Skipping install ..."
        }

    - name: Configure
      run: cmake -Wdev -Werror=dev -S . -B ./_build -G "Visual Studio 16 2019" -T v142 -A x64 -D CMAKE_SYSTEM_VERSION=8.1 -D FETCHCONTENT_BASE_DIR=${{ env.FETCH_CONTENT_DIR }} -D BASALT_WARNINGS_AS_ERRORS=ON

    - name: Build
      run: cmake --build ./_build --config ${{ matrix.configuration }} --parallel
