name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019

    env:
      DXSDK_DIR: "C:\Program Files (x86)\Microsoft DirectX SDK"

    steps:
    - uses: actions/checkout@v2

    - name: Cache DirectX SDK setup
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ${{env.temp}}/DXSDK_Jun10.exe
        key: June2010

    - name: Install DirectX SDK
      run: |
        $exePath = "$env:temp\DXSDK_Jun10.exe"
        if (-not(Test-Path -Path $exePath)) {
          Write-Host "Downloading..."
          (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)
        }

        Write-Host "Installing..."
        $installPath = "C:\Program Files (x86)\Microsoft DirectX SDK"
        cmd /c start /wait $exePath /P $installPath /U

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/_ci

    - name: Configure
      working-directory: ${{runner.workspace}}/_ci
      run: cmake -G "Visual Studio 16 2019" -A x64 ${env:GITHUB_WORKSPACE}

    - name: Build
      working-directory: ${{runner.workspace}}/_ci
      shell: bash
      run: cmake --build . --config Release
