name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: Write-Output "DXSDK_DIR=${env:TEMP}/Microsoft DirectX SDK" >> ${env:GITHUB_ENV}

    - name: Cache DirectX SDK
      uses: actions/cache@v2
      with:
        path: ${{env.DXSDK_DIR}}
        key: June2010-v2

    - name: Install DirectX SDK
      run: |
        if (-not(Test-Path -Path ${env:DXSDK_DIR})) {
          Write-Host "Downloading..."
          $exePath = "$env:temp\DXSDK_Jun10.exe"
          (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)

          Write-Host "Installing..."
          cmd /c start /wait $exePath /P ${env:DXSDK_DIR} /U
        } else {
          Write-Host "Using cached DirectX SDK. Skipping install ..."
        }

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/_ci

    - name: Configure
      working-directory: ${{runner.workspace}}/_ci
      run: cmake -G "Visual Studio 16 2019" -A x64 ${env:GITHUB_WORKSPACE}

    - name: Build
      working-directory: ${{runner.workspace}}/_ci
      shell: bash
      run: cmake --build . --config Release
