name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Install DirectX SDK
      run: |
        Write-Host "DirectX Software Development Kit..." -ForegroundColor Cyan

        Write-Host "Downloading..."
        $exePath = "$env:temp\DXSDK_Jun10.exe"
        (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)

        Write-Host "Installing..."
        $installPath = "C:\Program Files (x86)\Microsoft DirectX SDK"
        cmd /c start /wait $exePath /P $installPath /U
        Add-Path $installPath
        Add-SessionPath $installPath

        Remove-Item $exePath
        Write-Host "Installed" -ForegroundColor Green

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/_ci

    - name: Configure
      working-directory: ${{runner.workspace}}/_ci
      run: cmake -G "Visual Studio 16 2019" -A x64 ${env:GITHUB_WORKSPACE}

    - name: Build
      working-directory: ${{runner.workspace}}/_ci
      shell: bash
      run: cmake --build . --config Release
